#!/usr/bin/env bash

[[ -n ${ZSH_VERSION-} ]] &&
    APPDIR="$( dirname $0 )" ||
    APPDIR="$( dirname $BASH_SOURCE )"

[[ $APPDIR =~ ^/ ]] || APPDIR="$PWD/$APPDIR"

PATH="$APPDIR/lib:$PATH"

# completion
if [[ -n ${BASH_VERSION-} ]]; then
    source "$APPDIR/share/bash/tmux-perlbrew-switcher.bash"
    source "$APPDIR/share/bash/tmux-plenv-switcher.bash"
    source "$APPDIR/share/bash/tmux-pyenv-switcher.bash"
    source "$APPDIR/share/bash/tmux-rbenv-switcher.bash"

elif [[ -n ${ZSH_VERSION-} ]]; then
  # note this must happen before the compinit call in your .zshrc
  fpath=("$APPDIR/share/zsh" $fpath)

fi
