#!/usr/bin/env bash

TMUXVS_TOOL=pyenv
APPDIR="$( dirname $0 )"

tmuxvs:shell:pyenv() {
    command="pyenv shell"
}

tmuxvs:run:pyenv() {
    echo "fixme - not yet implemented";
    exit 1
}

source "$APPDIR/tmux-version-switcher"

