#!/usr/bin/env bash

TMUXVS_TOOL=perlbrew
APPDIR="$( dirname $0 )"

tmuxvs:local:perlbrew() {
    command="perlbrew use"
}

tmuxvs:run:perlbrew() {
    command="perl -wE'$1'"
}

source "$APPDIR/tmux-version-switcher"

