#!/usr/bin/env bash

TMUXVS_TOOL=rbenv
APPDIR="$( dirname $0 )"

tmuxvs:shell:rbenv() {
    command="rbenv shell"
}

tmuxvs:run:rbenv() {
    echo "fixme - not yet implemented";
    exit 1
}

source "$APPDIR/tmux-version-switcher"

