#!/usr/bin/env bash

TMUXVS_TOOL=plenv
APPDIR="$( dirname "$0" )"

tmuxvs:shell:plenv() {
    command="plenv shell"
}

tmuxvs:run:plenv() {
    command="perl -wE'$1'"
}

source "$APPDIR/tmux-version-switcher"

