#!/usr/bin/env bash

TMUXVS_TOOL=perlbrew
APPDIR="$( dirname $0 )"

tmuxvs:use:perlbrew() {
    command="perlbrew use"
}

tmuxvs:run:perlbrew() {
    local cmd="$1"

    command="perl -wE'$cmd'"
}

source "$APPDIR/tmux-version-switcher"

