#!/usr/bin/env bash

TMUXVS_TOOL=plenv
APPDIR="$( dirname $0 )"

tmuxvs:local:plenv() {
    command="plenv local"
}

tmuxvs:run:plenv() {
    command="perl -wE'$1'"
}

source "$APPDIR/tmux-version-switcher"

